# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llm_service_pb2 as llm__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/llm.LlmService/Generate',
                request_serializer=llm__service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=llm__service__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Optimize = channel.unary_unary(
                '/llm.LlmService/Optimize',
                request_serializer=llm__service__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=llm__service__pb2.OptimizeResponse.FromString,
                _registered_method=True)
        self.ExtractProfile = channel.unary_unary(
                '/llm.LlmService/ExtractProfile',
                request_serializer=llm__service__pb2.ExtractProfileRequest.SerializeToString,
                response_deserializer=llm__service__pb2.ExtractProfileResponse.FromString,
                _registered_method=True)
        self.EnhanceField = channel.unary_unary(
                '/llm.LlmService/EnhanceField',
                request_serializer=llm__service__pb2.EnhanceFieldRequest.SerializeToString,
                response_deserializer=llm__service__pb2.EnhanceFieldResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/llm.LlmService/Chat',
                request_serializer=llm__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=llm__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.UserChat = channel.unary_unary(
                '/llm.LlmService/UserChat',
                request_serializer=llm__service__pb2.UserChatRequest.SerializeToString,
                response_deserializer=llm__service__pb2.UserChatResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/llm.LlmService/Health',
                request_serializer=llm__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=llm__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class LlmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Optimize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnhanceField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=llm__service__pb2.GenerateRequest.FromString,
                    response_serializer=llm__service__pb2.GenerateResponse.SerializeToString,
            ),
            'Optimize': grpc.unary_unary_rpc_method_handler(
                    servicer.Optimize,
                    request_deserializer=llm__service__pb2.OptimizeRequest.FromString,
                    response_serializer=llm__service__pb2.OptimizeResponse.SerializeToString,
            ),
            'ExtractProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractProfile,
                    request_deserializer=llm__service__pb2.ExtractProfileRequest.FromString,
                    response_serializer=llm__service__pb2.ExtractProfileResponse.SerializeToString,
            ),
            'EnhanceField': grpc.unary_unary_rpc_method_handler(
                    servicer.EnhanceField,
                    request_deserializer=llm__service__pb2.EnhanceFieldRequest.FromString,
                    response_serializer=llm__service__pb2.EnhanceFieldResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=llm__service__pb2.ChatRequest.FromString,
                    response_serializer=llm__service__pb2.ChatResponse.SerializeToString,
            ),
            'UserChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UserChat,
                    request_deserializer=llm__service__pb2.UserChatRequest.FromString,
                    response_serializer=llm__service__pb2.UserChatResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=llm__service__pb2.HealthRequest.FromString,
                    response_serializer=llm__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LlmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LlmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/Generate',
            llm__service__pb2.GenerateRequest.SerializeToString,
            llm__service__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Optimize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/Optimize',
            llm__service__pb2.OptimizeRequest.SerializeToString,
            llm__service__pb2.OptimizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/ExtractProfile',
            llm__service__pb2.ExtractProfileRequest.SerializeToString,
            llm__service__pb2.ExtractProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnhanceField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/EnhanceField',
            llm__service__pb2.EnhanceFieldRequest.SerializeToString,
            llm__service__pb2.EnhanceFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/Chat',
            llm__service__pb2.ChatRequest.SerializeToString,
            llm__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/UserChat',
            llm__service__pb2.UserChatRequest.SerializeToString,
            llm__service__pb2.UserChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LlmService/Health',
            llm__service__pb2.HealthRequest.SerializeToString,
            llm__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
